Add bashate in gate jobs and fix existing errors
Change-Id: I3cbf754ea9c037df8b95eb6f83dbe8ce09bfd717
Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

diff --git a/scripts/upload-swift-artifacts b/scripts/upload-swift-artifacts
--- a/scripts/upload-swift-artifacts
+++ b/scripts/upload-swift-artifacts
@@ -43,31 +43,27 @@ function show_options {
     exit $1
 }
 
-function check_file
-{
-  local FILE=$1
-  supported_files=(" RPM " "gzip compressed data")
-  array_length=${#supported_files[@]}
+function check_file {
+    local FILE=$1
+    supported_files=(" RPM " "gzip compressed data")
+    array_length=${#supported_files[@]}
 
-  local test_type=`file $FILE`
+    local test_type=`file $FILE`
 
-  local i=0
-  local matched=0
+    local i=0
+    local matched=0
 
-  while [ $i -ne $array_length -a $matched -eq 0 ]
-  do
-    if [[ "$test_type" =~ ${supported_files[$i]} ]]
-    then
-      matched=1
+    while [ $i -ne $array_length -a $matched -eq 0 ]; do
+        if [[ "$test_type" =~ ${supported_files[$i]} ]]; then
+            matched=1
+        fi
+        i=$((i+1))
+    done
+
+    if [ $matched -eq 0 ]; then
+        echo "Not a supported file type: $FILE"
+        exit 1
     fi
-    i=$((i+1))
-  done
-
-  if [ $matched -eq 0 ]
-  then
-    echo "Not a supported file type: $FILE"
-    exit 1
-  fi
 
 }
 
@@ -99,22 +95,22 @@ while true ; do
 done
 
 if [ -z "${FILES:-}" ]; then
-  echo "Error: No files were specified."
-  exit 1
+    echo "Error: No files were specified."
+    exit 1
 fi
 
 if [ -z "${CONTAINER_NAME:-}" ]; then
-  echo "Error: No Swift --container was specified."
-  exit 1
+    echo "Error: No Swift --container was specified."
+    exit 1
 fi
 
-function create_heat_env() {
-  local heat_env_file=$1
-  mkdir -p $(dirname "$heat_env_file")
-  cat > "$heat_env_file" <<-EOF_CAT
+function create_heat_env {
+    local heat_env_file=$1
+    mkdir -p $(dirname "$heat_env_file")
+    cat > "$heat_env_file" <<-EOF_CAT
 # Heat environment to deploy artifacts via Swift Temp URL(s)
 parameter_defaults:
-  DeployArtifactURLs:
+    DeployArtifactURLs:
 EOF_CAT
 }
 
@@ -126,53 +122,53 @@ SWIFT_ACCOUNT=$(openstack container create $CONTAINER_NAME -f value -c account)
 SWIFT_INTERNAL_URL=$(openstack endpoint list | grep swift | grep internal | sed -e "s|.*\(http.*\)://\([^/]*\)/.*|\1://\2|" || true)
 
 if [ -z "$SWIFT_INTERNAL_URL" ]; then
-  # fallback to old openstack client 'show' which displays all the URLs
-  SWIFT_INTERNAL_URL=$(openstack endpoint show swift | grep internalurl | sed -e "s|.*\(http.*\)://\([^/]*\)/.*|\1://\2|")
+    # fallback to old openstack client 'show' which displays all the URLs
+    SWIFT_INTERNAL_URL=$(openstack endpoint show swift | grep internalurl | sed -e "s|.*\(http.*\)://\([^/]*\)/.*|\1://\2|")
 fi
 
 # Does the Temp-URL-Key exist on this container?
 # If not set it...
 KEY_SET=$(openstack container show $CONTAINER_NAME -c properties -f value 2>/dev/null | tr ',' '\n' | grep Temp-Url-Key || true)
 if [ -z $KEY_SET ]; then
-  echo "Creating new Swift Temp-URL-Key for container: $CONTAINER_NAME"
-  SWIFT_TEMP_URL_KEY=$(uuidgen | sha1sum | awk '{print $1}')
-  openstack container set --property "Temp-URL-Key=$SWIFT_TEMP_URL_KEY" "${CONTAINER_NAME}"
+    echo "Creating new Swift Temp-URL-Key for container: $CONTAINER_NAME"
+    SWIFT_TEMP_URL_KEY=$(uuidgen | sha1sum | awk '{print $1}')
+    openstack container set --property "Temp-URL-Key=$SWIFT_TEMP_URL_KEY" "${CONTAINER_NAME}"
 else
-  SWIFT_TEMP_URL_KEY=$(echo -n $KEY_SET | sed -rn "s/[[:space:]]*Temp-Url-Key='([[:alnum:]]+)'.*/\1/p")
+    SWIFT_TEMP_URL_KEY=$(echo -n $KEY_SET | sed -rn "s/[[:space:]]*Temp-Url-Key='([[:alnum:]]+)'.*/\1/p")
 fi
 
 if [ -n "${ENVIRONMENT_FILE:-}" ]; then
-  echo "Creating heat environment file: $ENVIRONMENT_FILE"
-  create_heat_env "$ENVIRONMENT_FILE"
+    echo "Creating heat environment file: $ENVIRONMENT_FILE"
+    create_heat_env "$ENVIRONMENT_FILE"
 else
-  echo "No environment file specified... skipping creation of Heat environment."
+    echo "No environment file specified... skipping creation of Heat environment."
 fi
 
 function get_tempurl {
-  # https://docs.openstack.org/swift/latest/api/temporary_url_middleware.html#hmac-sha1-signature-for-temporary-urls
-  local FILE="$1"
-  local SWIFT_METHOD='GET'
-  local SWIFT_PATH="/v1/${SWIFT_ACCOUNT}/${CONTAINER_NAME}/$(basename $FILE)"
-  local SWIFT_EXPIRES=$(( $(date '+%s') + $SECONDS ))
-  local SWIFT_SIG=$(printf '%s\n%s\n%s' $SWIFT_METHOD $SWIFT_EXPIRES $SWIFT_PATH | openssl sha1 -hmac $SWIFT_TEMP_URL_KEY | sed 's/^.* //')
-  echo -n "${SWIFT_PATH}?temp_url_sig=${SWIFT_SIG}&temp_url_expires=${SWIFT_EXPIRES}"
+    # https://docs.openstack.org/swift/latest/api/temporary_url_middleware.html#hmac-sha1-signature-for-temporary-urls
+    local FILE="$1"
+    local SWIFT_METHOD='GET'
+    local SWIFT_PATH="/v1/${SWIFT_ACCOUNT}/${CONTAINER_NAME}/$(basename $FILE)"
+    local SWIFT_EXPIRES=$(( $(date '+%s') + $SECONDS ))
+    local SWIFT_SIG=$(printf '%s\n%s\n%s' $SWIFT_METHOD $SWIFT_EXPIRES $SWIFT_PATH | openssl sha1 -hmac $SWIFT_TEMP_URL_KEY | sed 's/^.* //')
+    echo -n "${SWIFT_PATH}?temp_url_sig=${SWIFT_SIG}&temp_url_expires=${SWIFT_EXPIRES}"
 }
 
 function upload_file {
 
-  local FILE="$1"
-  echo "Uploading file to swift: $1"
-  pushd $(dirname $FILE) &>/dev/null
-  openstack object create "$CONTAINER_NAME" $(basename $FILE)
-  popd &>/dev/null
-  echo "Upload complete."
+    local FILE="$1"
+    echo "Uploading file to swift: $1"
+    pushd $(dirname $FILE) &>/dev/null
+    openstack object create "$CONTAINER_NAME" $(basename $FILE)
+    popd &>/dev/null
+    echo "Upload complete."
 
-  local URL=$(get_tempurl "$FILE")
-  echo "    - '${SWIFT_INTERNAL_URL}$URL'" >> $ENVIRONMENT_FILE
+    local URL=$(get_tempurl "$FILE")
+    echo "    - '${SWIFT_INTERNAL_URL}$URL'" >> $ENVIRONMENT_FILE
 
 }
 
 for FILE in ${FILES[@]}; do
-  check_file "$FILE"
-  upload_file "$FILE"
+    check_file "$FILE"
+    upload_file "$FILE"
 done
